[#17] create adding storyPoints for users
RYAZHAPOVILNUR/mentoring-users-app pull request #272
Opened 2024-04-28 06:55 UTC by TamirlanT

@Ha1Tamik добавление сторипоинтов для пользователей

2024-05-02 12:41 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +
убрать лишние пустые строки, сильно влияют на читабельность

2024-05-03 09:07 UTC, RYAZHAPOVILNUR commented
на доработку

2024-05-03 09:49 UTC, RYAZHAPOVILNUR requested changes

2024-05-03 09:49 UTC, RYAZHAPOVILNUR commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +
пустые строки убрать

2024-05-10 08:53 UTC, krymnon69 commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +export class UsersFilterComponent {
на самом деле этот компонент по факту является просто инпут компонентом с событием 
`@Output inputChange: string`,
а потом просто использовать
 `<custom-input (inputChange)="filterUsers($event)"/>
   filterUsers(filter: string)`

2024-05-11 08:59 UTC, closed without merging