pull recquests
RYAZHAPOVILNUR/mentoring-users-app pull request #283
Opened 2024-05-10 12:39 UTC by Kiki3471

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/data-access/src/lib/interfaces.ts
> +export interface MaterialRes {
кто такой этот ваш Res

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/data-access/src/lib/materials.facade.ts
> +  public readonly mats$: Observable<Material[]> = this.store.pipe(select(materialsSelector.selectMats));
излишние типы в селекторах

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-folder-create/src/lib/folders-add-button/folders-add-button.component.ts
> +  private readonly dialogAdd = inject(MatDialog);
по прежнему dialogAdd

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-content/src/lib/components/materials-content/materials-content.component.ts
> +  public readonly data = inject(MAT_DIALOG_DATA);
лучше указывать тип этих данных

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-create/src/lib/materials-add-button/materials-add-button.component.ts
> +  public addMat(name: string){
сокращение

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.html
> +  <br>
проигнорировано

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.ts
> +  public readonly formGroup: FormGroup = this.formBuilder.group({
: FormGroup - этим ты убил автоматическое присвоение типов.

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.ts
> +  private getValidators(){
лучше не стало. это должен быть enum ={
PDF = '/...\.pdf$/
}

потом можно брать enum[key], а не строить цепочку if/else

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-list/src/lib/materials-card/materials-card.component.html
> +    <mat-icon *ngIf="getType('.pdf') === true"> insert_drive_file</mat-icon>
чистый пайп.
=== тру = переусложенение

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/materials/feature-materials-list/src/lib/materials-card/materials-card.component.ts
> +  @Output() deleteMaterial: EventEmitter<number> = new EventEmitter();
дженерик лучше задать в new Emmiter<>

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/users/feature-users-detail/src/lib/users-detail-card/detail-users-card.component.ts
> +  public addPoints = false;
переменная имеет глагольное имя.
isAddedPoints

2024-05-25 11:09 UTC, krymnon69 commented on libs/users/users/feature-users-list/src/lib/user-filter/user-filter.component.ts
>      this.inputForm = new FormControl('');
сразу объявить не получилось?

2024-05-25 11:09 UTC, krymnon69 commented
Часть замечаний проигнорировано, дело твоё.
Вкраце посмотрел, отписался. Можешь не переделывать.
**_ПРИНЯТО_**

2024-06-20 00:20 UTC, RYAZHAPOVILNUR requested changes

2024-06-20 00:20 UTC, RYAZHAPOVILNUR commented on .gitignore
>  Thumbs.db
видны комменты от Евгения?

2024-07-18 13:50 UTC, closed without merging