[#2] Create feature materials by Ha1Tamik
RYAZHAPOVILNUR/mentoring-users-app pull request #285
Opened 2024-05-14 14:47 UTC by TamirlanT

2024-05-16 20:49 UTC, krymnon69 commented
Итого:
1. формтирование, местами промахиваешься, дал основные рекомендации. и не забывай смотреть на окружающий код, подчерпнёшь оттуда тоже.
2. глушишь ТС
3. ветка содержит код других задач
4. местами в шоке от гигантских функций лежащих рядом с компонентом

`НЕ ПРИНЯТО`, учти замечания и потихоньку готовься к собесам

2024-06-20 00:21 UTC, RYAZHAPOVILNUR requested changes

2024-06-20 00:21 UTC, RYAZHAPOVILNUR commented on apps/users/src/app/app.config.ts
>  import { tasksEffects, tasksFeature } from '@users/users/task/data-access';
видны комменты от Евгения?

2024-06-20 09:58 UTC, TamirlanT commented on apps/users/src/app/app.config.ts
>  import { tasksEffects, tasksFeature } from '@users/users/task/data-access';
Комменты видны, по ним, перед твоим комментарием commit с изменениями по замечаниям ("refact fix and refactoring")

2024-07-12 12:05 UTC, closed without merging