[2] (feat) Add Materials (@RadicNa30)
RYAZHAPOVILNUR/mentoring-users-app pull request #327
Opened 2024-07-05 00:01 UTC by pynhaXD

2024-07-08 08:51 UTC, freecree requested changes

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/data-access/src/lib/+state/materials.effects.ts
> +            return of(MaterialsActions.deleteFolderFailure({error}));
Здесь должно быть:
`return of(MaterialsActions.addFolderFailure({ error }));`

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/data-access/src/lib/+state/materials.reducer.ts
> +}
Думаю, лучше разбить этот редьюсер на два, отдельно для Folder, и для Material. Это повысит читабельность, можно будет обновлять materials через EntityAdapter и для каждой сущности будут свои error и статус, что сделает код более предсказуемым и позволит избежать ненужных багов

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/feature-folders-list/src/lib/folders-list/folders-list.component.ts
> +  @Output() folderToOpen = new EventEmitter<number>();
Нейминг не очень, deleteFolder, openFolder читается получше

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.ts
> +  }
Лучше сделать кастомным валидатором

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.html
> +      [disabled]="formGroup.invalid || !linkValidator(this.formGroup.value.material_link!)"
Выглядит не очень. Если сделать linkValidator кастомным валидатором, а не просто методом, то можно будет написать просто formGroup.invalid

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/feature-materials-create/src/lib/materials-add-button/materials-add-button.component.html
> +  <button mat-menu-item (click)="onOpenAddMaterialDialog('подкаст')">Подкаст</button>
'Видео', 'PDF', 'подкаст' лучше вынести в отдельный enum, так легко ошибиться + значения лучше указывать на английском

2024-07-08 08:51 UTC, freecree commented on libs/users/materials/feature-materials-list/src/lib/materials-card/materials-card.component.ts
> +  }
Этот метод уже 2 раза повторяется, лучше его вынести в отдельную утилиту. 'video', 'pdf', 'audio' лучше сделать через enum

2024-07-16 14:21 UTC, RYAZHAPOVILNUR approved these changes

2024-07-17 13:38 UTC, freecree approved these changes

2024-07-18 13:58 UTC, closed without merging