Add user point
RYAZHAPOVILNUR/mentoring-users-app pull request #339
Opened 2024-07-23 15:39 UTC by ShanShan323

2024-07-23 15:45 UTC, ShanShan323 commented
Немного накосячил с гит:( наверное нужно было принять изменения с прошлой задачи

2024-07-30 08:55 UTC, RYAZHAPOVILNUR requested changes

2024-07-30 08:55 UTC, RYAZHAPOVILNUR commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          purchaseDate: '22.07.2024',
почему здесь моковые данные?

2024-08-06 10:58 UTC, ShanShan323 commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          purchaseDate: '22.07.2024',
Забыл убрать, исправил.

2024-09-06 12:10 UTC, closed without merging