#3 Добавить фильтр в список пользователей
RYAZHAPOVILNUR/mentoring-users-app pull request #400
Opened 2024-12-11 13:36 UTC by zhansaulet

- добавила компонент users-filter для фильтрации пользователей в странице Пользователи
- добавила инпут с помощью formControl
- добавила нужные селекторы, изменения в редьюсере, фасаде и в сторе

tg: @zhansaule_t

2024-12-19 06:22 UTC, zhansaulet commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +    this.filterFormControl.valueChanges.pipe(filter((value): value is string => value !== null)).subscribe((value) => {
добавила

2024-12-19 09:12 UTC, asylbekovkairat requested changes

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: {
так как вы здесь указали usersFilter как объект, и в селекторах также нужно его сделать объектом

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +      user.username?.toLowerCase().includes(lowerCaseFilter) || user.email?.toLowerCase().includes(lowerCaseFilter)
вы получаете в filteredUser поле name и по нему фильтруете массив по username и по email. 
Тут нужно смотреть на описание задачи, если указано сделать, только по имени, то используем только имя. Если сказано, что можно и по email и по name, то в таком случае вместо filteredUser.name, сделать filteredUser.searchQuery

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-detail/src/lib/users-detail-card/detail-users-card.component.html
> +              <button mat-icon-button matSuffix type="button" aria-label="submit updated totalStoryPoints"  *ngIf="vm.editMode"(click)="onCloseUser()">
почему на кнопку done вызывается onCloseUser?

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-detail/src/lib/users-detail-card/detail-users-card.component.html
> +                <mat-icon>add</mat-icon>
почему на кнопку add вызывается onCloseUser?

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-detail/src/lib/users-detail-card/detail-users-card.component.ts
> +    console.log(vm);
удалить лог

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.html
> +      <input type="text" matInput [formControl]="filterFormControl"
форматирование слетело

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.scss
> +    width: 400px;
старайтесь избегать статичных значений по типу px

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.spec.ts
> +  it('should create', () => {
будет лучше назвать "should render correctly", более привычное для многих программистов.

Также если компонент зависит от входных данных, то можно назвать "should render correctly with given props"

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  private usersFacade = inject(UsersFacade);
добавьте readonly для usersFacade

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  private subscription: Subscription = new Subscription();
добавьте readonly для subscription

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +          return this.usersFacade.filterUsers(value);
можно написать в одну строку .subscribe((value) => this.usersFacade.filterUsers(value);

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-filter></users-filter>
если внутрь ничего не будете передавать, то лучше использовать одинарный тег <users-filter />

2024-12-19 09:12 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +import { MatIconModule } from '@angular/material/icon';
сортировка импортов нужно

VsCode
ctrl+shift+p => sort impors

2024-12-23 06:41 UTC, asylbekovkairat requested changes

2024-12-23 06:41 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  if (!filteredUser.name) return users;
после if добавьте empty line

2024-12-23 06:41 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  const lowerCaseFilter = filteredUser.name?.toLowerCase();
хорошая практика выносит операции над строкой в переменную, для сокращения, кода 👍 
Но в данному случае `filteredUser.name?.toLowerCase()` можно напрямую написать в includes в return. что сократить код

Лучше выносить в переменную, когда происходят операции по сложнее или даже если операция легкая, но длина вышла большой, в таких случаях можно вынести в переменную
можете не исправлять, но в будущем знайте.

2024-12-23 06:41 UTC, asylbekovkairat commented on libs/users/users/feature-users-detail/src/lib/users-detail-card/detail-users-card.component.ts
>      if (vm.editMode) {
тут можно написать без else 

`if (vm.editMode) this.formGroup.enable();`

 `this.formGroup.disable();`

2024-12-23 06:41 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/index.ts
> +
удалите лишний empty line

2024-12-26 09:07 UTC, asylbekovkairat requested changes

2024-12-26 09:07 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Page] Filter Users', props<{ filter: { name: string } }>());
создайте тип UsersFIlter с помощью которого вы будете типизировать все месте где он будет нужен 

`type UsersFilter = { name: string }`

2024-12-26 09:07 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +    this.store.dispatch(UsersActions.setUsersFilter({ filter: { name: searchQuery } }));
используйте type UsersFilter

2024-12-26 09:07 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  filterUsers(searchQuery: string) {
обычно фильтрация делается по разным полям и для этого удобно использовать объект, который передается в бэкенд.

Сделайте так чтобы метод filterUsers принимал объект типа UsersFilter и сразу же его передавал в action

2024-12-26 09:07 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: {
type UsersFilter

2024-12-26 09:07 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +      .subscribe((value) => this.usersFacade.filterUsers(value));
добавьте отписку

2024-12-30 07:47 UTC, zhansaulet commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +      .subscribe((value) => this.usersFacade.filterUsers(value));
разве код на 27 линии не является отпиской?

2024-12-30 15:31 UTC, asylbekovkairat requested changes

2024-12-30 15:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export type usersFilter = {
Типы и интерфейсы нужно называть с большой буквы

2024-12-30 15:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  filterUsers(searchQuery: UsersActions.usersFilter) {
Почему тип параметра это Action? можно напрямую импортировать тип

2024-12-30 15:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: UsersActions.usersFilter;
Почему тип параметра это Action? можно напрямую импортировать тип

2024-12-30 15:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  destroyRef = inject(DestroyRef);
private readonly destroyRef

2024-12-30 15:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  public filterFormControl = new FormControl('');
можно поставить readonly? если да то поставьте

2024-12-30 15:55 UTC, asylbekovkairat approved these changes

2025-01-07 06:37 UTC, closed without merging