Задание 1 (фильтрация юзеров)
RYAZHAPOVILNUR/mentoring-users-app pull request #401
Opened 2024-12-12 17:34 UTC by shepherd1422

#3
Добавить фильтр в список пользователей. Создать компонет users-filter.component в папке libs/users/users/feature-users-list и добавить его в компонент users-list-container.component.html над users-list-ui

Добавить в компоненте users-filter.component фильтр у которого будет инпут "Имя", реализовать с помощью formControl, при заполнении поля пользователи должны фильтроваться. (https://youtu.be/042FrC8NVvs?si=DaNr19WK_uoEAhcv)) ВИДЕО ПО РАБОТЕ С ФОРМАМИ

Создать action setUsersFilter который будет принимать данные {filter: {name: string}} (в файле libs/users/users/data-access/src/lib/+state/users.actions.ts)

В редьюсере users.reducer создать новое поле usersFilter: {name: string} в UsersState и в initialUsersState,  повесть обработчик экшена setUsersFilter в редьюсере с помощью on, на срабатывание экшена класть данные из этого экшена в state

Создать селектор usersFilterSelector который будет из стора вытягивать поле usersFilter

Добавить новый селектор filteredUsers который будет включать в себя два других селектора (usersFilter и allUsers) и на выход будут даваться уже отфильтрованные данные, если фильтр пустой то возвращать всех пользователей

В фасад libs/users/users/data-access/src/lib/+state/users.facade.ts добавить поле filteredUsers$ и использовать в нем селектор selectFilteredUsers

В файле libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.store.ts в методе setUsersFromGlobalToLocalStore заменить this.usersFacade.allUsers$ на this.usersFacade.filteredUsers$

2024-12-19 07:31 UTC, asylbekovkairat requested changes

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Filter] Sort Users by Name' ,  props< { filter: {name: string} } >());
форматирование слетело

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  public filteredUsers$ = this.store.select(selectFilteredUsers);
добавьте readonly

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: {name: string};
форматирование слетело

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: {name: ''},
форматирование слетело

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    if (userFilter && userFilter.name && allUsers) {
условие можно сократить вот так 
!userFilter.name ? allUsers : allUsers.filter((user) => user.name.toLowerCase().includes(userFilter.name.toLowerCase()))

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +import { UsersFilterComponent } from '../../../users-filter.component';
сортировка импортов нужно

VsCode
ctrl+shift+p => sort impors

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +import { UsersFilterComponent } from '../../../users-filter.component';
почему то не применился allias

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
>    private readonly router = inject(Router);
инжектирован встроенных классов от angular ставить выше остальных

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +  public filteredUsers$ = this.componentStore.users$;
используйте users.facade

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +      map(users => users.filter((user) => user.name.toLowerCase().includes(searchTerm.toLowerCase())))
фильтрацию не нужно делать в компоненте, логика фильтрации у вас лежит в selectors

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter.component.ts
> +  constructor() { this.name.valueChanges.pipe( debounceTime(200) ).subscribe(value => { this.filterUsers.emit(value); }); }
форматирование слетело

2024-12-19 07:31 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter.component.ts
> +  @Output() filterUsers = new EventEmitter();
@Output лучше поставить выше, чем  name = new FormControl('');

2025-03-10 07:38 UTC, shepherd1422 commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +      map(users => users.filter((user) => user.name.toLowerCase().includes(searchTerm.toLowerCase())))
как это? у меня она ест в selectors и юзается на фасаде? 

export const selectFilteredUsers = createSelector(
  usersFilterSelector,
  selectAllUsers,
  (userFilter , allUsers) => {
    return !userFilter.name
      ? allUsers
      : allUsers.filter((user) =>
        user.name.toLowerCase().includes(userFilter.name.toLowerCase()));
  }
)

2025-05-12 09:27 UTC, closed without merging