Users filter feature from KhaoKai
RYAZHAPOVILNUR/mentoring-users-app pull request #403
Opened 2024-12-17 08:58 UTC by ramshido

2024-12-18 15:55 UTC, RYAZHAPOVILNUR approved these changes

2024-12-19 07:13 UTC, asylbekovkairat requested changes

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  if (!usersFilter.name.trim()) {
это условие можно написать сокращенно, так как не так много кода в теле условия 
 if (!usersFilter.name.trim()) return allUsers;

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.scss
> +    width: 400px;
советую избегать статичных значений в px, так как при адаптивке будет сложно. Лучше использовать padding или относительные значения, как %

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.scss
> +    width: 30px !important;
старайтесь избегать !important, так как это является не лучшей практикой.
Почитайте про приоритеты стилей https://code-basics.com/ru/languages/css/lessons/priority

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.spec.ts
> +  it('should create', () => {
будет лучше назвать "should render correctly", более привычное для многих программистов. 

Также если компонент зависит от входных данных, то можно назвать "should render correctly with given props"

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +import { UsersFacade } from '@users/users/data-access';
отсортируйте импорты, локальные импорты лучше вставлять в самый конец

в VsCode: 
ctrl + shift + p -> sort imports

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  public usersFacade = inject(UsersFacade);
private readonly usersFacade

Фасады лучше приватизировать

2024-12-19 07:13 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-list-ui [vm]="vm" (deleteUser)="onDeleteUser($event)"
форматирование слетело

2025-05-12 09:28 UTC, closed without merging