Users filter
RYAZHAPOVILNUR/mentoring-users-app pull request #404
Opened 2024-12-20 05:07 UTC by Daniil0684

@sivak_misvak

2024-12-22 13:21 UTC, asylbekovkairat requested changes

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Filter] Users Filtered', props<{ filter:{ name: string }}>())
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: string }
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: '' }
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    if (!filter.name) {
можно написать без else

`  if (filter.name.trim() === '') {`

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +
удалите этот empty line

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  private  readonly store = inject(Store)
после private лишний пробел

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +        this.store.dispatch(setUsersFilter({ filter: { name: value ?? ''}}))
слетело форматирование

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-users-filter></users-users-filter>
можно использовать одинарный тег, если не прокидываете Child

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
>  <create-users-button></create-users-button>
можно использовать одинарный тег, если не прокидываете Child

2024-12-22 13:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +import { BehaviorSubject, combineLatest, map } from 'rxjs';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-31 15:36 UTC, Daniil0684 commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Filter] Users Filtered', props<{ filter:{ name: string }}>())
вроде бы исправил

2024-12-31 15:37 UTC, Daniil0684 commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: string }
здесь тоже вроде бы исправил

2024-12-31 15:42 UTC, Daniil0684 commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: '' }
это не исправил

2025-01-01 04:56 UTC, asylbekovkairat requested changes

2025-01-01 04:56 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
>    usersFilter = new FormControl('');
добавляйте модификаторы доступа и readonly по надобности

2025-01-01 04:56 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
>    private readonly destroyRef = inject(DestroyRef);
inject рядом с inject

2025-01-03 03:23 UTC, asylbekovkairat requested changes

2025-01-03 03:23 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export type  UsersFilter = { name: string };
лишний пробел после type

2025-01-03 03:23 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Filter] Users Filtered', props<{ filter: UsersFilter }>())
название action не корректное, почему Filtered в прошедшем времени. Лучше просто Set Users Filter

2025-01-03 03:23 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  usersFilter = new FormControl('');
добавьте модификаторы доступа и readonly если это возможно

2025-01-03 03:23 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-users-filter/>
после users-users-filter и между /> должен быть пробел

2025-01-03 03:23 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +
лишняя строка

2025-03-02 11:44 UTC, closed without merging