добавил фильтрации юзеров
RYAZHAPOVILNUR/mentoring-users-app pull request #408
Opened 2024-12-21 07:34 UTC by Zeiddho

сделал фильтрацию с кнопки, надо еще попробоать сделать динамичски

мой тг @fly_likeabutterfly

2024-12-22 12:54 UTC, asylbekovkairat requested changes

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Filter] Filter Users', props<{ filter: { name: string } }>())
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  filterUsers(filter: { name: string }) {
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: string };
можно создать тип

type UsersFilter { name: string;  }

и переиспользовать его везде

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  (allUsers, usersFilter) => usersFilter
usersFilter всегда будет true, так как это объект, нужно проверять по конкретной значению

Перепишите условие

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  ? allUsers.filter((user) => user.name.toLowerCase().includes(usersFilter.name.toLowerCase()))
попробуйте написать обычным if else будет более читабельнее

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.html
> +    <svg xmlns="http://www.w3.org/2000/svg" height="36px" viewBox="0 -960 960 960" width="36px" fill="#5f6368"><path d="M784-120 532-372q-30 24-69 38t-83 14q-109 0-184.5-75.5T120-580q0-109 75.5-184.5
слетело форматирование

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.html
> +    <input type="text" matInput formControlName="name" placeholder="Ex. Иван Иванов"/>
фидбэк по placeholder

1) инпут для ввода имени, но в примере показано Имя + Фамилия
2) Ex. не сразу понятно, лучше определится с языком и писать по одному языку или если мультиязычный, то добавлять переводы
3) placeholder можно даже и не ставить, так как в label показан смысл инпута

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
>  import { USERS_FEATURE_KEY, UsersState, usersAdapter } from './users.reducer';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  userFilterForm!: FormGroup;
public? private? readonly?

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  @Output() filterUsersWidow = new EventEmitter<string>();
@Output ставит лучше в самый верх компоненты

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +    event.preventDefault();
после event.preventDefault() нужно поставить empty line, дабы разделить визуально логику

2024-12-22 12:54 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
>  import { UsersListComponent } from '../users-list/users-list.component';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-25 07:42 UTC, Zeiddho commented
Сделал фильтрацию динамичной. Но при возврате назад после перехода на карточку юзера поле инпута пустое, и показан последний набранный результат. Как исправить чтобы при возврате назад после просмотра карточки юзера выпадал весь список пользователей, или чтобы в поле оставался последний набранный результат?
Возможно надо использовать Router… Но не уверен что на данном м задании нужно туда залезать… 
Дай, пожалуйста, фидбек по этому поводу

2024-12-26 04:47 UTC, asylbekovkairat requested changes

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    if(usersFilter) {
1) слетело форматирование 
2) можно написать более лаконично
`if (usersFilter) allUsers.filter((user) => user.name.toLowerCase().includes(usersFilter.name.toLowerCase()))`
`return allUsers;`

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  public userFilterForm!: FormGroup;
если можно поставить readonly, то лучше поставить

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  @Output() filterUsersWidow = new EventEmitter<string>();
@Output и @Input ставить в самом верху и после них оставлять empty line

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +      if (value === '') {
1) filterUsersWidow - фильтр пользователей вдова?) нужно filterUsersWindow, или filterUsersModal если это модальное окно
2) не вижу смысла в условии if else, можно без него написать `this.filterUsersWidow.emit(value)` и все будет работать. Я сохрану скрин и отправлю его вам в тг, на созвоне в пятницу я более подробно объясню вам про свой коммент, пока исправьте

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +    (filterUsersWidow)="onFilterUsersList($event)"
filterUsersWidow, widow это вдова)) нужно window

2024-12-26 04:47 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +  onFilterUsersList(filter: string) {
На самом деле, он должен принимать объект UsersFilter, и передать его в фасад, где далее исходя от этого объекта отправится запрос на бэк, 

Фильтрация обычно делается по нескольким полям и бэк принимает их всегда в объекте

2024-12-26 05:40 UTC, asylbekovkairat commented
> Сделал фильтрацию динамичной. Но при возврате назад после перехода на карточку юзера поле инпута пустое, и показан последний набранный результат. Как исправить чтобы при возврате назад после просмотра карточки юзера выпадал весь список пользователей, или чтобы в поле оставался последний набранный результат? Возможно надо использовать Router… Но не уверен что на данном м задании нужно туда залезать…  Дай, пожалуйста, фидбек по этому поводу

как я понял, user flow такой

пользователь отфильтровал, по имени например, потом перешел по карточку пользователя, возвращается назад на страницу с пользователями и видит что инпут пустой, но результат отфильтрован.

Правильная работа, должна быть такой, фильтры не должны сбрасывать если произошел переход по карточке и если обратно зайти на предыдующую страницу с фильтрами, фильтры должны быть заполнены. 

Это можно сделать вот так:
синхронизировать фильтры и URL. Например: Пользователь ввел в фильтры по имени Вася, и отфильтровал список. URL в такой случае должен выглядять, как https:localhost:3000/users?name=Вася. 
Плюсы, если вы отправите такую ссылку другому пользователю, он открыв  ее увидит сразу отфильтрованных пользователей по имени "Вася". Но нужно дописать код, который также отслеживает URL строку и парсит ее в объект

И при переходе обратно на предыдущую страницу фильтры сохранятся

2024-12-26 06:22 UTC, Zeiddho commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  public userFilterForm!: FormGroup;
не получается, т к тут вылетает ошибка

  private createFilterForm() {
    this.userFilterForm = this.fb.group({ // Attempt to assign to const or readonly variable 
      name: [''],
    });
  }

2024-12-26 06:23 UTC, Zeiddho commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  @Output() filterUsersWidow = new EventEmitter<string>();
понял

2024-12-26 06:42 UTC, Zeiddho commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +  onFilterUsersList(filter: string) {
я че то пытался поменять в аргументах, но теперь кажется я тебя понял.

2024-12-28 06:41 UTC, Zeiddho commented
почему-то этот код не работает 
    if (usersFilter) allUsers.filter((user) => user.name.toLowerCase().includes(usersFilter.name.toLowerCase()))
    return allUsers;

2024-12-28 06:46 UTC, Zeiddho commented
> > Сделал фильтрацию динамичной. Но при возврате назад после перехода на карточку юзера поле инпута пустое, и показан последний набранный результат. Как исправить чтобы при возврате назад после просмотра карточки юзера выпадал весь список пользователей, или чтобы в поле оставался последний набранный результат? Возможно надо использовать Router… Но не уверен что на данном м задании нужно туда залезать… >  Дай, пожалуйста, фидбек по этому поводу
> 
> как я понял, user flow такой
> 
> пользователь отфильтровал, по имени например, потом перешел по карточку пользователя, возвращается назад на страницу с пользователями и видит что инпут пустой, но результат отфильтрован.
> 
> Правильная работа, должна быть такой, фильтры не должны сбрасывать если произошел переход по карточке и если обратно зайти на предыдующую страницу с фильтрами, фильтры должны быть заполнены.
> 
> Это можно сделать вот так: синхронизировать фильтры и URL. Например: Пользователь ввел в фильтры по имени Вася, и отфильтровал список. URL в такой случае должен выглядять, как https:localhost:3000/users?name=Вася. Плюсы, если вы отправите такую ссылку другому пользователю, он открыв ее увидит сразу отфильтрованных пользователей по имени "Вася". Но нужно дописать код, который также отслеживает URL строку и парсит ее в объект
> 
> И при переходе обратно на предыдущую страницу фильтры сохранятся

да, так и есть
Я пытался сделать насколько мог, но в основном все это сводится к обращению к GPT, т к мне сложно понять как устроен router на проекте.
Может ты мне подскажешь куда копать и как сделать это правильно.

2024-12-28 08:39 UTC, Zeiddho commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    if(usersFilter) {
почему-то этот код не работает

2024-12-28 16:27 UTC, asylbekovkairat requested changes

2024-12-28 16:27 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    // if (usersFilter) allUsers.filter((user) => user.name.toLowerCase().includes(usersFilter.name.toLowerCase()))
удаляйте комментарии

2024-12-28 16:27 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    } else {
можете убрать else и просто оставить return allUsers

2024-12-28 16:27 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  public userFilterForm!: FormGroup;
пустая строка до constructor и уберите пустую строку до userFilterForm

2025-01-18 19:06 UTC, Zeiddho commented
К задаче по Сторипоинтам:
1. Добавил input для totalStoryPoints с кнопки,
2. Сделал возможным установление числа 0 в строке totalStoryPoints,
3. В методе disableStoryPointsInput() прописал чтобы на кнопке отмены ввода в строке totalStoryPoints возвращалось существующее, а не введенное значение
4. Я решил не создавать отдельный тип type onSuccessSPonCbType = () => void, т к изменение Сторипоинтов происходит так же как и редактирование юзера и в той же самой форме. В общем не вижу логики в этом. У нас есть такой же тип onSuccessEditionCbType
5. Упростил Эффект addStoryPoints, т к на функционал пропущенные строки из эффекта editUser не влияют.

2025-01-19 03:30 UTC, asylbekovkairat approved these changes

2025-05-12 09:28 UTC, closed without merging