#3 дабавил фильтр в список пользователей
RYAZHAPOVILNUR/mentoring-users-app pull request #409
Opened 2024-12-21 13:10 UTC by RuslanDev777

2024-12-21 16:53 UTC, YusupOzdoyev commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  throw new Error('Function not implemented.');
удали

2024-12-22 12:44 UTC, asylbekovkairat requested changes

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
>  import * as UsersActions from './users.actions';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  public readonly filteredUsers$ = this.store.select(UsersSelectors.filtredUsersSelector);
нужно назвать filteredUsersSelector* в this.store.select(UsersSelectors.filtredUsersSelector);

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: string };
можно создать тип 

`type UsersFilter {
name: string; 
}`

и переиспользовать его везде

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
>  import { USERS_FEATURE_KEY, UsersState, usersAdapter } from './users.reducer';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +export function filtredUsers(filtredUsers: any): import('rxjs').OperatorFunction<any, any> {
не используйте any, нужно типизировать

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +  if (!usersfFilter.name) {
можно написать в одну строку 
if (!usersFilter.name) return allUsers;

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.scss
> +
лишний отступ

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +import { MatButtonModule } from '@angular/material/button';
нужно сортировка для импортов 
Vscode - ctrl+shift+p -> sort imports

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-filter/users-filter.component.ts
> +  readonly usersFacade$ = inject(UsersFacade);
private readonly

2024-12-22 12:44 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-filter></users-filter>
если в Child ничего не передаете, можно использовать одинарный тег

2025-05-12 09:28 UTC, closed without merging