materials
RYAZHAPOVILNUR/mentoring-users-app pull request #411
Opened 2024-12-23 13:16 UTC by OqTooTpO

tg: @o8iIUIi8o

2024-12-24 12:35 UTC, OqTooTpO commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +      // delay(1500),
уже раскомментировала везде

2024-12-26 05:28 UTC, asylbekovkairat requested changes

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/core/pipes/custom-pipes.ts
> +    if (string.length > limit) {
можно сократить код вот так 
 `if (string.length > limit) string.slice(0, limit) + '...';`
 `return string;`

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/core/pipes/custom-pipes.ts
> +  transform(string: string, limit: number) {
название string очень абстрактное, и string: string выглядит странно, не думаете?) 

думаю название value, inputValue, text будет получше

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.actions.ts
> +export const deleteFolderFailed = createAction('[Folders/Api] Delete Folder Failed', props<{ error: any }>());
лучше типизировать error

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +            console.error('Error', error);
удаляйте логи, пройдитесь по всему коду и удалите их

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +          map((folders) => {
в стрелочных фукнциях вы можете сокращать код 
 `map((folders) => FolderActions.loadFoldersSuccess({ folders });`
 
 так как => является аналогом return, но это работает если мало кода

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +            return of(FolderActions.loadFoldersFailure({ error }));
тут тоже можете сократить как выше

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +      // delay(1500),
коммент удалить

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.effects.ts
> +          catchError((error) => {
можно сократить код

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-folders/folders.selectors.ts
> +
все селекторы можно не разъединять с помощью empty line

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-materials/materials.effects.ts
> +import { ApiService } from '@users/core/http';
сортировка импортов 
VsCode
Ctrl+shift+p -> sort imports

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/+state-materials/materials.selectors.ts
> +
можно объединить все createSelector

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/data-access/src/lib/constants-enums/materials-regex.ts
> +export const regexMaterials = {
файд будет лучше назвать materials-validation, так как суффикс regex, редко используется

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-create/src/lib/folders-add-button/folders-add-button.component.ts
> +      .subscribe((result) => {
добавьте отписку 

и можно сократить код 
`if (result) this.FoldersFacade.addFolder(result);`

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-card/folders-card.component.ts
> +  folder!: FoldersVM;
добавьте модификаторы доступа для folder

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-card/folders-card.component.ts
> +  @Output() deleteFolder = new EventEmitter();
Output и Input должны быть в самом верху

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-card/folders-card.component.ts
> +    const date = new Date(time);
`const formattedDateString =` `${date.getDate()} 
    ${date.toLocaleString('default', { month: 'short' }).slice(0, -1)} 
    ${date.getFullYear()}`
    
    `return formattedDateString `
    
    + добавьте empty line перед return

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list-container/folders-list-container.component.ts
> +
лишний empty line

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list-container/folders-list-container.store.ts
> +import { foldersVMAdapter } from '../../../../view-models/folders-vm.adapter';
сортируйте импорты, это нужно для последовательности загрузки пакетов, сначала внешние, а потом внутренние

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list-container/folders-list-container.store.ts
> +  private readonly dialog = inject(MatDialog);
перед folders$ можно поставить empty line. это будет визуально отделять инжектирование зависимостей и локальные состояния

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list-container/folders-list-container.store.ts
> +        tap((result: boolean) => {
`tap((result: boolean) => result && this.FoldersFacade.deleteFolder(folder.id))`

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list/folders-list.component.ts
> +  vm!: FoldersListVM;
модификаторы доступа

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-folders-list/src/lib/folders-list/folders-list.component.ts
> +  @Output() deleteFolder = new EventEmitter();
Output и Input должны стоять в самом верху

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-content/src/lib/materials-content/materials-content.component.scss
> +      width: 600px;
лучше избегать статичных width

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-create/src/lib/materials-add-button/materials-add-button.component.ts
> +      .subscribe((result) => {
добавьте отписку

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-create/src/lib/materials-add-dialog/materials-add-dialog.component.ts
> +  public readonly data = inject(MAT_DIALOG_DATA);
inject рядом с inject поставьте

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-list/src/lib/materials-card/materials-card.component.ts
> +    return `${date.getDate()}
посмотрите комменты выше где был formattedDateString

скорее всего функцию formatDate можно вынести в отдельный файл и переиспользовать

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-list/src/lib/materials-list-container/materials-list-container.component.ts
> +  private readonly FoldersFacade = inject(FoldersFacade);
перед materials$ можно поставить empty line

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-list/src/lib/materials-list-container/materials-list.container.store.ts
> +  private readonly dialog = inject(MatDialog);
перед materials$ можно поставить empty line

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/task/src/lib/task-change-dialog/task-change-dialog.component.ts
> +      if (!isNaN(parsedValue)) {
сократите if else

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export type UsersFilter = {
круто, класс, вау

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          catchError((error) => {
вот сверху класса идет, и тут опять return, сократите до стрелочной функции как выше

2024-12-26 05:28 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +    return users.filter(user => user.name.toLowerCase().includes(filter.name.toLowerCase()));
можно убрать return.
а что если filter.name окажется null

2024-12-28 17:01 UTC, asylbekovkairat requested changes

2024-12-28 17:01 UTC, asylbekovkairat commented on libs/users/materials/feature-materials-list/src/lib/materials-list-container/materials-list.container.store.ts
> +        tap((result: boolean) => {
` tap((result: boolean) => result && this.MaterialsFacade.deleteMaterial(material.id))`

2025-01-07 05:11 UTC, asylbekovkairat approved these changes

2025-01-07 06:54 UTC, closed without merging