#17 make the students' profile display the story points
RYAZHAPOVILNUR/mentoring-users-app pull request #414
Opened 2024-12-26 16:31 UTC by KoznovDm

https://t.me/Alexsandrovichhhhh

2024-12-28 16:24 UTC, asylbekovkairat requested changes

2024-12-28 16:24 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +            console.error('Error', error);
удалите лог

2024-12-29 12:43 UTC, KoznovDm commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +            console.error('Error', error);
fix

2024-12-29 13:12 UTC, asylbekovkairat requested changes

2024-12-29 13:12 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[Users Page] Set Users Filter', props<{ filter: UsersFilter }>());
создайте тип UsersFilter
`type UsersFilter { name: string; }` который будете везде использовать 

здесь объяснил подробно https://t.me/c/1811120492/25533

2024-12-29 13:12 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          map(({ userData }) => {
в стрелочных функциях,стрелка  => играет роль return, и если код после return можно написать в одну строку, лучше сократить, как вы это сделали с tap на 157 строке 
`map(({ userData }) => UsersActions.addStoryPointsSuccess({ userData }))`

2024-12-29 13:12 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          catchError((error) => {
см комментарий выше по сокращению

2024-12-29 13:35 UTC, KoznovDm commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          map(({ userData }) => {
fix

2024-12-29 13:35 UTC, KoznovDm commented on libs/users/users/data-access/src/lib/+state/users.effects.ts
> +          catchError((error) => {
fix

2024-12-30 14:53 UTC, asylbekovkairat approved these changes

2025-01-08 08:04 UTC, closed without merging