Выполнил ДЗ по фильтрации юзеров
RYAZHAPOVILNUR/mentoring-users-app pull request #418
Opened 2024-12-30 16:35 UTC by Holin1945

2024-12-31 02:42 UTC, asylbekovkairat requested changes

2024-12-31 02:42 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.actions.ts
> +export const setUsersFilter = createAction('[setUsersFilter] SetUsersFilter', props<{ name: string }>());
создайте тип UsersFilter
`type UsersFilter = { name: string }`
 
 Этот тип вы можете использовать везде

2024-12-31 02:42 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.facade.ts
> +  filterUser(name: string) {
Более корректное название будет onUsersFilter, который принимает в параметр объект с типом UsersFilter (см. комментарий выше).

Референс https://t.me/c/1811120492/25533

2024-12-31 02:42 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.reducer.ts
> +  usersFilter: { name: string };
type UsersFilter (см комм выше)

2024-12-31 02:42 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +     (user) => user.name.includes(usersFilter.name)
нужно сделать фильтрацию, чтобы она не зависила от UpperCase, lowercase, CAPS

2025-01-07 05:21 UTC, asylbekovkairat requested changes

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +export const usersFilterSelector = createSelector(selectUsersState, (state: UsersState) => state.usersFilter);
нейминг хороший, но лучше придерживаться общих принятых правил по проекту. В вашем случае, нужно selectUsersFilter

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/data-access/src/lib/+state/users.selectors.ts
> +export const filteredUsers = createSelector(
тут нужно будет selectFilteredUsers

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/index.ts
> +
удалите лишнюю строку

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-users-filter (UserFilter)="onFilterUser($event)"></users-users-filter>
<users-users-filter (UserFilter)="onFilterUser($event)" />

если не прокидываете Child в компоненту, лучше написать как одинарный тег

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.ts
> +  onFilterUser(name: UsersFilter) {
корректнее будет назвать onUserFilter, так как фильтрация проходит над пользователями

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter/users-filter.component.ts
> +  filterUsers = new FormControl('',[Validators.required]);
добавьте модификаторы доступа и readonly если можно

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter/users-filter.component.ts
> +
удалите пустую строку

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter/users-filter.component.ts
> +    ) .subscribe(value => {
перед .subscribe удалите пробел

добавьте отписку

2025-01-07 05:21 UTC, asylbekovkairat commented on libs/users/users/feature-users-list/users-filter/users-filter.component.ts
> +        this.UserFilter.emit({name: value})
вокруг name: value поставьте пробелы

добавьте форматировщик Prettier в ютубе гляньте

2025-01-07 08:15 UTC, Holin1945 commented on libs/users/users/feature-users-list/users-filter/users-filter.component.ts
> +        this.UserFilter.emit({name: value})
Prettier  есть, иногда забываю отформатировать, а так привычка выработана, я перфекционист немного ))

2025-01-07 08:17 UTC, Holin1945 commented on libs/users/users/feature-users-list/src/lib/users-list-container/users-list-container.component.html
> +  <users-users-filter (UserFilter)="onFilterUser($event)"></users-users-filter>
не знал что так можно, Кайрат, а для чего это нужно ?  прописывать одинарный тег, а не двойной ?

2025-05-12 09:28 UTC, closed without merging